version: '3'
services:
    mysql:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_DATABASE=obo
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=123456
        volumes:
            - mysql-data:/var/lib/mysql
            - ./obo.sql:/docker-entrypoint-initdb.d/init.sql
    web:
        depends_on:
            - mysql
        image: obo-spring:latest
        ports:
            - "8005:8080"
volumes:
    mysql-data: